#pragma once
#ifndef __HAL_CONTROL_FLASHOPERATION_H__
#define __HAL_CONTROL_FLASHOPERATION_H__ 

#define HAL_FLASH_PAGE_SIZE 2048

#define HAL_FLASH_AVAILABLE_START_ADDR (0x08000000 + (15 * HAL_FLASH_PAGE_SIZE))
#define HAL_FLASH_AVAILABLE_END_ADDR   (0x08000000 + (16 * HAL_FLASH_PAGE_SIZE))


#define HAL_FLASH_AVAILABLE_SIZE = (HAL_FLASH_AVAILABLE_END_ADDR - HAL_FLASH_AVAILABLE_START_ADDR)


#include "HAL_GlobalConfig.h"
#include "HAL_Control_Error.h"


#endif
